name: otof-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas=2.3.3
  - numpy=2.3.5
  - matplotlib=3.10.6
  - seaborn=0.13.2
  - scipy=1.16.3
  - requests=2.32.5
  - jupyter=1.1.1
  - notebook=7.4.5
  - ipykernel=6.31.0
  - statsmodels=0.14.5
  - biopython=1.87
  - pip
  - pip:
    - plotly==6.3.0
    - kaleido>=0.2.1
